############################
## MacOS Persistence Pack ##
############################
./Modules/ASEP/ls_la_Library_LaunchDaemons.zsh
./Modules/ASEP/ls_la_Library_LaunchAgents.zsh
./Modules/ASEP/ls_la_Users_ALL_Library_LaunchAgents.zsh
./Modules/ASEP/find_LaunchAgents_LaunchDaemons_plist_mtime_7.zsh
./Modules/ASEP/find_LaunchAgents_plutil_ProgramArguments.zsh
./Modules/ASEP/grepE_lol_bins_ALL_plist.zsh
./Modules/ASEP/sfltool_dumpbtm.zsh
./Modules/ASEP/launchctl_print_system.zsh
./Modules/ASEP/macos_login_items.zsh
./Modules/Audit/profiles_show_all.zsh
./Modules/Audit/systemextensionsctl_list.zsh
./Modules/Audit/unsigned_persistence_executables.zsh
./Modules/Audit/launchservices_dump.zsh
