############################
## MacOS Initial Triage   ##
############################
./Modules/SystemInfo/uname_a.sh
./Modules/SystemInfo/uptime.sh
./Modules/SystemInfo/dscl_list_users.zsh
./Modules/SystemInfo/dscl_read_Groups_admin_GroupMembership.zsh
./Modules/RunningProcesses/ps_axwwo_user_pid_ppid_command.zsh
./Modules/Network/lsof_i_n_P.sh
./Modules/Network/scutil_proxy.zsh
./Modules/Network/scutil_dns.zsh
./Modules/ASEP/sfltool_dumpbtm.zsh
./Modules/ASEP/launchctl_print_system.zsh
./Modules/ASEP/macos_login_items.zsh
./Modules/Audit/spctl_status.zsh
./Modules/Audit/csrutil_status.zsh
./Modules/Audit/fdesetup_status.zsh
./Modules/Audit/systemextensionsctl_list.zsh
./Modules/Audit/sqlite3_TCC_system_access.zsh
./Modules/Audit/codesign_running_processes.zsh
./Modules/Audit/unsigned_persistence_executables.zsh
./Modules/Audit/launchservices_dump.zsh
./Modules/Logs/log_show_gatekeeper_xprotect_mrt_last_7d.zsh
./Modules/DiskUsage/find_Users_recent_dmg_pkg_mobileconfig.zsh
./Modules/DiskUsage/xattr_quarantine_recent_Users.zsh
