#######################
## Crypto Miner Pack ##
#######################
./Modules/RunningProcesses/ps_aux.sh
./Modules/RunningProcesses/ps_axjf.sh
./Modules/RunningProcesses/lsof.sh
./Modules/Network/lsof_i_n_P.sh
./Modules/Network/lsof_i_n_P_grep_established.sh
./Modules/SystemInfo/cpu_load.sh
./Modules/SystemInfo/uptime.sh
./Modules/ASEP/crontab_l.sh
./Modules/ASEP/crontab_u_root_l.sh
./Modules/ASEP/systemctl_list_timers_all.sh
./Modules/DiskUsage/find_size_PLUS10000k_print.sh
./Modules/DiskUsage/find_uid_0_perm_4000_print.sh
