#################################
## Linux/Unix Compromise Pack  ##
#################################
./Modules/SystemInfo/uname_a.sh
./Modules/SystemInfo/uptime.sh
./Modules/SystemInfo/w_whos_logged_in.sh
./Modules/SystemInfo/getent_etc_passwd_egrep_UID0.sh
./Modules/SystemInfo/getent_passwd_uid_gid_anomalies.sh
./Modules/RunningProcesses/ps_aux.sh
./Modules/RunningProcesses/ps_axjf.sh
./Modules/RunningProcesses/lsof.sh
./Modules/RunningProcesses/lsof_deleted_files.sh
./Modules/Network/ss_tulpn.sh
./Modules/Network/lsof_i_n_P.sh
./Modules/ASEP/systemctl_list_units_service_running.sh
./Modules/ASEP/systemctl_list_units_type_service.sh
./Modules/ASEP/systemctl_list_timers_all.sh
./Modules/ASEP/systemctl_list_user_services.sh
./Modules/ASEP/find_systemd_unit_files_writable.sh
./Modules/ASEP/find_shell_startup_files.sh
./Modules/ASEP/cat_etc_ld_so_preload.sh
./Modules/ASEP/crontab_l.sh
./Modules/ASEP/crontab_u_root_l.sh
./Modules/Audit/cat_pam_configs.sh
./Modules/Audit/getcap_recursive_interesting_paths.sh
./Modules/Audit/ssh_authorized_keys_provenance.sh
./Modules/InstalledApplications/recent_package_activity.sh
./Modules/Containers/docker_ps_a.sh
./Modules/Containers/podman_ps_a.sh
./Modules/Containers/crictl_ps_a.sh
./Modules/Logs/last.sh
./Modules/Logs/lastb.sh
./Modules/Logs/journalctl_COMM_sudo_COMM_su.sh
./Modules/Logs/journalctl_SYSTEMD_logind_service.sh
./Modules/Logs/journalctl_u_ssh.sh
