##############################
## Forensic Deep Triage Pack #
##############################
./Modules/SystemInfo/uname_a.sh
./Modules/SystemInfo/uptime.sh
./Modules/SystemInfo/w_whos_logged_in.sh
./Modules/SystemInfo/cat_etc_hosts.sh
./Modules/SystemInfo/cat_etc_passwd.sh
./Modules/SystemInfo/getent_passwd_uid_gid_anomalies.sh
./Modules/RunningProcesses/ps_aux.sh
./Modules/RunningProcesses/ps_axjf.sh
./Modules/RunningProcesses/lsof.sh
./Modules/RunningProcesses/lsof_deleted_files.sh
./Modules/Network/lsof_i_n_P.sh
./Modules/Network/ss_tulpn.sh
./Modules/Network/netstat_tuapnv.sh
./Modules/NetworkInfo/ifconfig_a.sh
./Modules/NetworkInfo/arp_a.sh
./Modules/ASEP/crontab_l.sh
./Modules/ASEP/crontab_u_root_l.sh
./Modules/ASEP/systemctl_list_units_service_running.sh
./Modules/ASEP/systemctl_list_timers_all.sh
./Modules/ASEP/systemctl_list_user_services.sh
./Modules/ASEP/find_systemd_unit_files_writable.sh
./Modules/ASEP/find_shell_startup_files.sh
./Modules/ASEP/cat_etc_ld_so_preload.sh
./Modules/ASEP/sfltool_dumpbtm.zsh
./Modules/ASEP/launchctl_print_system.zsh
./Modules/ASEP/macos_login_items.zsh
./Modules/Audit/cat_pam_configs.sh
./Modules/Audit/getcap_recursive_interesting_paths.sh
./Modules/Audit/ssh_authorized_keys_provenance.sh
./Modules/Audit/systemextensionsctl_list.zsh
./Modules/Audit/sqlite3_TCC_system_access.zsh
./Modules/Audit/codesign_running_processes.zsh
./Modules/Audit/unsigned_persistence_executables.zsh
./Modules/Audit/eslogger_list_events.zsh
./Modules/Audit/launchservices_dump.zsh
./Modules/Logs/log_show_gatekeeper_xprotect_mrt_last_7d.zsh
./Modules/Logs/log_show_predicate_com_apple_TCC_Refusing_last_72h.zsh
./Modules/InstalledApplications/recent_package_activity.sh
./Modules/Containers/docker_ps_a.sh
./Modules/Containers/podman_ps_a.sh
./Modules/Containers/crictl_ps_a.sh
./Modules/Browsers/browser_extensions.zsh
./Modules/DiskUsage/xattr_quarantine_recent_Users.zsh
./Modules/DiskUsage/find_Users_recent_dmg_pkg_mobileconfig.zsh
