###############################
## Network and Process Pack  ##
###############################
./Modules/RunningProcesses/ps_aux.sh
./Modules/RunningProcesses/ps_axjf.sh
./Modules/RunningProcesses/lsof.sh
./Modules/RunningProcesses/lsof_plusL1.sh
./Modules/RunningProcesses/lsof_deleted_files.sh
./Modules/Network/lsof_i_n_P.sh
./Modules/Network/lsof_i_n_P_grep_established.sh
./Modules/Network/ss_tulpn.sh
./Modules/Network/netstat_tuapnv.sh
./Modules/NetworkInfo/ifconfig_a.sh
./Modules/NetworkInfo/arp_a.sh
