#########################
## SSH Compromise Pack ##
#########################
./Modules/SystemInfo/w_whos_logged_in.sh
./Modules/SystemInfo/cat_etc_passwd.sh
./Modules/Audit/cat_etc_ssh_sshd_config.sh
./Modules/Audit/for_each_user_cat_authorized_keys.zsh
./Modules/Audit/ssh_authorized_keys_provenance.sh
./Modules/Audit/md5sum_authorized_keys.sh
./Modules/Logs/last.sh
./Modules/Logs/lastb.sh
./Modules/Logs/grep_sshd_var_log_auth.sh
./Modules/Logs/zgrep_sshd_var_log_auth_all.sh
./Modules/Network/lsof_i_n_P.sh
./Modules/RunningProcesses/ps_aux.sh
